apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-tracker-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: devops-tracker
  
  source:
    repoURL: 'https://github.com/Ramiz-Takildar/devops_daily_tracker'
    targetRevision: develop
    path: k8s/overlays/dev
    kustomize:
      images:
        - ramiztakildar/devops-tracker-backend:dev-latest
        - ramiztakildar/devops-tracker-frontend:dev-latest
  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: devops-tracker-dev
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  
  revisionHistoryLimit: 10
