apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-tracker-prod

resources:
  - ../../base
  - hpa.yaml
  - network-policy.yaml
  - pdb.yaml

nameSuffix: -prod

patches:
  - path: namespace-patch.yaml
  - path: configmap-patch.yaml
  - path: replica-patch.yaml
  - path: resource-limits.yaml

images:
  - name: devops-tracker-backend
    newName: ramiztakildar/devops-tracker-backend
    newTag: v1.0.0
  - name: devops-tracker-frontend
    newName: ramiztakildar/devops-tracker-frontend
    newTag: v1.0.0
