apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-tracker-prod

bases:
  - ../../base

nameSuffix: -prod

patchesStrategicMerge:
  - namespace-patch.yaml
  - configmap-patch.yaml
  - replica-patch.yaml
  - resource-limits.yaml

resources:
  - hpa.yaml
  - network-policy.yaml
  - pdb.yaml

images:
  - name: devops-tracker-backend
    newName: ramiztakildar/devops-tracker-backend
    newTag: v1.0.0
  - name: devops-tracker-frontend
    newName: ramiztakildar/devops-tracker-frontend
    newTag: v1.0.0
